### ISSUE TITLE
Profiling messenger in Datadog seems off

### ISSUE THREAD

**Issue by clemherreman** [sourceability/instrumentation#9]
Hi :)

I'm struggling to give meaning to how data goes to Datadog. Traces & spans seems to mix the `messenger:consume` command, and the individual consumed messages

Here's an example :

![image](https://user-images.githubusercontent.com/272812/159325890-6b3d2163-21dc-42c2-9b8c-6602d4f37623.png)

You can see individual messages around a ~2-5s, but the first consumed one is always -5-7minutes, which is likely to be the worker process restart time (10 min),

My config is the following:

```yaml
# config/sourceability_instrumentation.yaml
sourceability_instrumentation:
  profilers:
    datadog:
      enabled: true

  listeners:
    command:
      enabled: true

    messenger:
      enabled: true
```

```yaml
#config/messenger.yaml
framework:
    messenger:
        buses:
            messenger.bus.default:
                middleware:
                    - Sourceability\Instrumentation\Messenger\ProfilerMiddleware
```

Am I doing something wrong? Are the messenger listener & messenger middlewares stepping on each others toes?
